Core/Model/Processor.cs

As it is described in [the MSPC manuscript](https://academic.oup.com/bioinformatics/article/31/17/2761/183989#) peaks are classified as the following: 
- Stringent peak: `p-value < TauS`
- Weak peak: `TauW < p-value <= TauS`
- Noise: `p-value >= TauW`  
However, it was implemented as the following: 
- Stringent peak: `p-value < TauS`
- Weak peak: `TauW <= p-value <= TauS` (`TauW` is inclusive, should have been exlusive)
- Noise: `p-value > TauW`  (`TauW` is exclusive, it should have been inclusive)
This PR fixes this issue.

Peaks with p-value less than TauW are considered weak

---

CLI/Export/ExporterBase.cs
Core.Tests/Classification/StringentConfirmed.cs
Core.Tests/Classification/StringentDiscarded.cs
Core.Tests/Classification/WeakConfirmed.cs
Core.Tests/Classification/WeakDiscarded.cs
Core.Tests/Example/Eg1.cs
Core/Comparers/CompareByValue.cs
Core/Model/Messages.cs
Core/Model/Peak.cs
Core/Model/ProcessedPeak.cs
Core/Model/Processor.cs
Core/Model/Sets.cs
Core/Model/SupportingPeak.cs

- Refactor properties of the `ProcessedPeak` class to adhere with the pascal naming convention;
- Set the accessibility of all properties of the `ProcessedPeak` class to private, and receive all the values via constructors; 
- Create `Peak` class and set it as the base for `ProcessedPeak` and `SupportingPeak` classes.

Overhaul ProcessedPeak class

---

Core.Tests/Example/Eg1.cs
Core.Tests/SetsAndAttributes/BackgroundPeaks.cs
Core.Tests/SetsAndAttributes/Confirmed.cs
Core.Tests/SetsAndAttributes/Discarded.cs
Core.Tests/SetsAndAttributes/Stringent.cs
Core.Tests/SetsAndAttributes/Weak.cs
Core/Model/Result.cs
Core/Model/Sets.cs

The number of peaks with a given attribute can be retrieved from `_sets` property (which is exposed via `Get` method). Hence, keeping a count of attributes as a separate property is unnecessary and makes code more complicated and difficult to test. Therefore, this property of the `Sets` type is removed.

Remove Stats property of the Sets class.

---

CLI/Export/ExporterBase.cs
Core.Tests/Example/Eg1.cs
Core.Tests/SetsAndAttributes/BackgroundPeaks.cs
Core.Tests/SetsAndAttributes/Stringent.cs
Core.Tests/SetsAndAttributes/Weak.cs
Core/Model/ProcessedPeak.cs
Core/Model/Processor.cs
Core/Model/Sets.cs

The `Sets` type has two properties `_sets` and `_setsInit`, which are used to store processed (i.e., peaks with `Confirmed`, `Stringent`, `True-Positive`, and `False-Positive` attributes) and pre-processed (i.e., peaks with `Stringent`, `Weak` and `Background` attributes) peaks respectively. This PR stores all peaks (both processed and pre-processed) in the `_sets` property, hence removes `_setsInit`.

Pre-processed and processed peaks are all stored as processed peaks

---

Core.Tests/Base/ColocalizationCount.cs
Core.Tests/Example/Eg1.cs
Core.Tests/SetsAndAttributes/BackgroundPeaks.cs
Core.Tests/SetsAndAttributes/Confirmed.cs
Core.Tests/SetsAndAttributes/Discarded.cs
Core.Tests/SetsAndAttributes/Stringent.cs
Core.Tests/SetsAndAttributes/Weak.cs
Core/Model/Processor.cs
Core/Model/Sets.cs
Core/Model/UpdateProcessedPeak.cs

MSPC stores separately `ProcessedPeaks` with different attributes. For instance, it stores `Confirmed` peaks in a different list (i.e., `_sets[Attributes.Confirmed]`) than `Discarded` peaks (i.e., `_sets[Attributes.Discarded]`). To ensure that a single peaks is either `Confirmed` or `Discarded` (no peak is both `Confirmed` and `Discarded`), MSPC post-processed `_sets` in `ProcessIntermediaSets` method of the `Process` class. 
However, the code the relation between `Classifications` property of processed peaks and separated list, is confusing and cumbersome to implement/debug and test. Therefore, this PR creates a single dictionary, called `_peaks` that stores all the processed peaks in a single data structure regardless of attributes of the processed peaks. 
Some other advantages of this …

Store all the peaks in a single data structure

---

CLI.Tests/CLI.Tests.csproj
CLI.Tests/CLIOptions.cs
CLI/CLI.csproj
CLI/CommandLineOptions.cs
MSPC.sln

Previously the `CommandLineOptions` class (a class that defines command line arguments, their default and valid values, throws exceptions on missing values, and defines _help_) was based on a library called [CommandLine](https://github.com/commandlineparser/commandline). This library is very intuitive and simple to use; however, I have a lot of issues running it under .NET Core. Therefore, I decided to re-implement the `CommandLineOptions` class leveraging `Microsoft.Extensions.CommandLineUtils` which works as expected in .NET Core.

Update CommandLineOptions class leveraging `Microsoft.Extensions.CommandLineUtils` and add required unit tests. 

---

Core.Tests/SetsAndAttributes/Confirmed.cs
Core/Functions/Processor.cs
Core/Model/Options.cs

If a (given or computed) p-value requires more precision than the limit of double type (`±5.0E−324` to `±1.7E308`), it (a) safely rounds a to `0`, and (b) does not break any mspc operation.

Do not define a max p-value, and remove related checks

---

CLI.Tests/CLIOptions.cs
CLI/CommandLineOptions.cs

With input samples being specified via wildcard chars (e.g., `"`, or `?`), some shell programs expand the expression and some does not, before invoking MSPC with those args. This PR fixes a bug with wildcard chars expanded before passing to MSPC.

Fix a bug with reading input samples specified via wildcard chars expanded at shell-level

---

CLI.Tests/Main.cs
CLI.Tests/ParserConfig.cs
CLI/Orchestrator.cs
CLI/ParserConfig.cs
CLI/Program.cs

ParserConfig is extended with the following new keys: 
- p-value format;
- default p-value;
- drop a parsed peak if a valid p-value is not parsed for the peak

Extend ParserConfig

---

CLI/Export/Exporter.cs
CLI/Orchestrator.cs
CLI/SummaryStats.cs

Filenames for ID-filename mapping are stored with file extension, and the extension is removed when file is exported. This extension should also be removed when creating summary statistics. 
This PR implements logic to remove file extension when creating the mapping hash table.

Fix a bug formatting summary statistics

---

CLI/CLI.csproj

This fixes the bug MSPC failing when a given input only contains `chr start stop`, but the parser configuration provides column number for all the attributes.

Update to use GeUtilities v5.3 

---

Core.Tests/Basic/MultipleIntersections.cs
Core/Functions/Processor.cs
Core/Model/ProcessedPeak.cs
Core/Mspc.cs
Core/MspcGeneric.cs

built based on https://github.com/Genometric/MSPC/pull/72

Make tracking a list of overlapping peaks an optional feature, which is disabled by default

---

Core.Tests/Basic/ColocalizationCount.cs
Core/Functions/Processor.cs
Core/IntervalTree/Node.cs
Core/IntervalTree/NodeData.cs
Core/IntervalTree/Tree.cs
Core/Model/Peak.cs

Testing on a dataset that consists of 279 samples and 1,756,215 peaks: 
**63%** faster performance:
|     |  Runtime (seconds) |
| --- | --------: | 
| Before (dev branch) | 1,327| 
|  After (this PR)  | 488|
**59%** less objects, and **52%** smaller heap size. 
|     |  Objects   |    Heap Size  |
| -- | ----------: | --------------: |
| Before (dev branch) | 14,181,393 | 730,555.22 KB |
| After (this PR)   | 5,719,617  |  345,039.23 KB |

Collapse multiple interval trees into a single tree. 

---

Core/Functions/Processor.cs

- **88%** (or **8.7x**) faster performance w.r.t https://github.com/Genometric/MSPC/pull/77;
- **95%** (or **23.7x**)  faster performance w.r.t. using one interval tree per sample (i.e., before https://github.com/Genometric/MSPC/pull/77).
|     |  Runtime (seconds) |
| --- | --------: | 
| Before PR https://github.com/Genometric/MSPC/pull/77 |  1,327 |
| With PR https://github.com/Genometric/MSPC/pull/77 | 488| 
|  This PR (built on https://github.com/Genometric/MSPC/pull/77)   | 56 |

Improve processing Supporting peaks.

---

appveyor.yml

This will fix the following error: the preview mode, along with the 'sonar.analysis.mode' parameter, is no more supported. You should stop using this parameter.

Drop SonarScanner preview mode

---

CLI.Tests/Table.cs
CLI/Logging/Logger.cs
CLI/Logging/Table.cs

This PR implements: 
- makes table independent from the logger, hence it does not log directly rather it returns the message to be logged to the logger itself;
- fixes a bug truncating the content of a table column; 
- adds unit tests for the `Table` class. 
Fixes https://github.com/Genometric/MSPC/issues/81

Fix a bug truncating column content 

---

CLI.Tests/CLIOptions.cs
CLI.Tests/Main.cs
CLI.Tests/ParserConfig.cs
CLI/CommandLineOptions.cs
CLI/Logging/Logger.cs
CLI/Orchestrator.cs

- Write all exceptions messages in _red_ color; 
- Implement an static logger method to be used when logger is not available; 
- Add `Error: ` prefix to all exception messages; 
- Set the colour of section title to _yellow_ and remove following blank line;
- Write the finish message in _green_.

Formatting and colouring error and success messages.

---

CLI.Tests/Main.cs
CLI/Logging/Logger.cs
CLI/Orchestrator.cs

Reports elapsed time as the following in the output: 
```
Elapsed time: 00:00:03.2534564
All processes successfully finished.
```

Report elapsed time in the output.

---

ValidationScripts/hg19_annotations/hg19.conf.txt
ValidationScripts/hg19_annotations/merged/CpG_islands_hg19.mrg.txt
ValidationScripts/hg19_annotations/merged/Enhancers_hg19.mrg.txt
ValidationScripts/hg19_annotations/merged/KnownGenes_hg19_exons.mrg.txt
ValidationScripts/hg19_annotations/merged/KnownGenes_hg19_introns.mrg.txt
ValidationScripts/hg19_annotations/merged/KnownTranscripts_hg19_coding.mrg.txt
ValidationScripts/hg19_annotations/merged/KnownTranscripts_hg19_nonCoding.mrg.txt
ValidationScripts/hg19_annotations/merged/KnownTranscripts_hg19_nonRefSeq.mrg.txt
ValidationScripts/hg19_annotations/merged/KnownTranscripts_hg19_promoters.mrg.txt
ValidationScripts/hg19_annotations/merged/miRNA_hg19.mrg.txt
ValidationScripts/hg19_annotations/merged/snoRNA_hg19.mrg.txt
ValidationScripts/hg19_annotations/merged/tRNA_hg19.mrg.txt
ValidationScripts/hg38_annotations/hg38.conf.txt
ValidationScripts/hg38_annotations/merged/CpG_islands_hg38.bed
ValidationScripts/hg38_annotations/merged/Enhancers_hg19_to_hg38.bed
ValidationScripts/hg38_annotations/merged/KnownGene_Gencode29_hg38_RefSeq_coding.bed
ValidationScripts/hg38_annotations/merged/KnownGene_Gencode29_hg38_RefSeq_noncoding.bed
ValidationScripts/hg38_annotations/merged/KnownGene_Gencode29_hg38_exons.bed
ValidationScripts/hg38_annotations/merged/KnownGene_Gencode29_hg38_introns.bed
ValidationScripts/hg38_annotations/merged/KnownGene_Gencode29_hg38_nonRefSeq.bed
ValidationScripts/hg38_annotations/merged/KnownGene_Gencode29_hg38_promoters.bed
ValidationScripts/hg38_annotations/merged/miRNA_hg38.bed
ValidationScripts/hg38_annotations/merged/snoRNA_hg38.bed
ValidationScripts/hg38_annotations/merged/tRNA_hg38.bed

Annotations are moved to this repository: https://github.com/Genometric/Annotations
ping @fernandoPalluzzi @marziacremona

Remove annotation files stored via LFS

---

appveyor.yml

The CodeCoverage.exe command is not recognized, hence, it throws exception when running on appveyor.

Fix code cov bug

---

CLI.Tests/CLI.Tests.csproj
CLI/CLI.csproj
CLI/Export/Exporter.cs
Core.Tests/Core.Tests.csproj
Core/Core.csproj

Addresses the issue reported at https://github.com/Genometric/MSPC/issues/131.

Report `inf` as a result of converting 0 to -Log10 format

---

CLI.Tests/Main.cs
CLI/Orchestrator.cs
CLI/Program.cs

Xref: https://github.com/Genometric/MSPC/issues/142
Sets exit code (`Environment.ExitCode`) as it follows: 
| Status         | Exit Code  |
| ------------ | ----------- |
| Successful  | `0`             |
| Error           | `1`             |

Set ExitCode according to the termination status

---

CLI.Tests/CLI.Tests.csproj
CLI.Tests/CLIOptions.cs
CLI.Tests/Main.cs
CLI/CLI.csproj
CLI/CommandLineOptions.cs
CLI/Logging/Logger.cs
CLI/Orchestrator.cs

If the user provides `n` samples but sets `c` to a value more than `n`, the algorithm will work correctly however `c>n` is confusing. Therefore, this PR implements the following: 
- Sets `c <= n`; for instance if `2` samples are given but `c=300%`, the value of `c` will be auto-corrected to `c=2` (or `100%`).
- A warning will be displayed for incorrect but auto-corrected `c` values.

Adjust maximum value of C according to the number of given input samples

---

CLI.Tests/Main.cs
CLI/CommandLineOptions.cs
CLI/Logging/Logger.cs
CLI/Orchestrator.cs
website/docs/cli/args.md
website/docs/cli/output.md
website/docs/quick_start.md

Export results to a given output directory and log the absolute path

---

CLI.Tests/Main.cs
CLI/Logging/Logger.cs
CLI/Orchestrator.cs

The export path is reported as the following on the console: 
```
.\mspc.exe -i .\rep*.bed -r bio -w 1e-4 -s 1e-8
Export Directory: C:\mspc\session_20210314_212356641
Degree of parallelism is set to 8.
.::...Parsing Samples....::.
----    --------------------    -----------     -----------     ------------    -----------
1/2                    rep1         53,697      2.239E-074       1.085E-003     1.000E-002
2/2                    rep2         37,717      5.370E-301       1.520E-004     9.550E-003
.::..Analyzing Samples...::.
...
```

Report the export path on console

---

Benchmark/PerformanceTest.cs
Benchmark/Result.cs
Benchmark/SyntheticReps.cs
Benchmark/VersionInfo.cs

Improvements to the benchmarking scripts

---

Benchmark/CLI/CommandLineInterface.cs
Benchmark/Program.cs
Benchmark/VersionInfo.cs

Improvements to the benchmarking script

---

Benchmark/Program.cs
Benchmark/VersionInfo.cs

Invoke MSPC in the benchmarking script in a cross-platform way; i.e., `dotnet mspc.dll`. 
The only caveat is that this type of invocation is supported on the latest versions; mainly since `v4`. Earlier versions need further testing, but some versions are not expected to support since they are not cross-platform; `v1` in particular.

Improve portability of benchmarking script

---

CLI/Orchestrator.cs
Core.Tests/Concurrency/Concurrency.cs
Core.Tests/PublicMembers.cs
Core/Functions/ConsensusPeaks.cs
Core/Functions/FalseDiscoveryRate.cs
Core/Functions/Processor.cs
Core/Mspc.cs
Core/MspcGeneric.cs

This improves performance as it allows mspc to utilize as many threads as the underlying scheduler provides, hence can better leverage the available system resources.

Set the default max degree of parallelism to the max allowed by the underlying scheduler

---

CLI.Tests/Main.cs
Core.Tests/Basic/TConsensusPeaks.cs

A few tests are added and updated to assert if peaks on different chromosomes and strands are all exported.

Extend tests asserting if peaks on all chrs and strands are exported

---

CLI.Tests/Main.cs
CLI/Orchestrator.cs

This PR fixes a bug where MSPC is not reporting a correct number of the identified consensus peaks on the terminal. The issue is related to the recently added stranded analysis (https://github.com/Genometric/MSPC/pull/176), where MSPC wrote in the terminal the number of strands instead of the peak count for consensus peaks. 
This PR adds a unit test to reproduce the issue and fixes the bug. 
Thanks to @MeriemBahda for reporting this bug!

Fix a bug reporting incorrect number of consensus peaks on the terminal
